package com.winlator.xserver;

/**
 * Java transcription of Winlator's XKeycode.kt. The vendored X server is otherwise pure Java,
 * and the .NET Android build compiles Java sources only, so the one Kotlin enum is restated here.
 */
public enum XKeycode {
    KEY_NONE((byte) 0),
    KEY_ESC((byte) 9),
    KEY_1((byte) 10),
    KEY_2((byte) 11),
    KEY_3((byte) 12),
    KEY_4((byte) 13),
    KEY_5((byte) 14),
    KEY_6((byte) 15),
    KEY_7((byte) 16),
    KEY_8((byte) 17),
    KEY_9((byte) 18),
    KEY_0((byte) 19),
    KEY_MINUS((byte) 20),
    KEY_EQUAL((byte) 21),
    KEY_BKSP((byte) 22),
    KEY_TAB((byte) 23),
    KEY_Q((byte) 24),
    KEY_W((byte) 25),
    KEY_E((byte) 26),
    KEY_R((byte) 27),
    KEY_T((byte) 28),
    KEY_Y((byte) 29),
    KEY_U((byte) 30),
    KEY_I((byte) 31),
    KEY_O((byte) 32),
    KEY_P((byte) 33),
    KEY_BRACKET_LEFT((byte) 34),
    KEY_BRACKET_RIGHT((byte) 35),
    KEY_ENTER((byte) 36),
    KEY_CTRL_L((byte) 37),
    KEY_A((byte) 38),
    KEY_S((byte) 39),
    KEY_D((byte) 40),
    KEY_F((byte) 41),
    KEY_G((byte) 42),
    KEY_H((byte) 43),
    KEY_J((byte) 44),
    KEY_K((byte) 45),
    KEY_L((byte) 46),
    KEY_SEMICOLON((byte) 47),
    KEY_APOSTROPHE((byte) 48),
    KEY_GRAVE((byte) 49),
    KEY_SHIFT_L((byte) 50),
    KEY_BACKSLASH((byte) 51),
    KEY_Z((byte) 52),
    KEY_X((byte) 53),
    KEY_C((byte) 54),
    KEY_V((byte) 55),
    KEY_B((byte) 56),
    KEY_N((byte) 57),
    KEY_M((byte) 58),
    KEY_COMMA((byte) 59),
    KEY_PERIOD((byte) 60),
    KEY_SLASH((byte) 61),
    KEY_SHIFT_R((byte) 62),
    KEY_KP_MULTIPLY((byte) 63),
    KEY_ALT_L((byte) 64),
    KEY_SPACE((byte) 65),
    KEY_CAPS_LOCK((byte) 66),
    KEY_F1((byte) 67),
    KEY_F2((byte) 68),
    KEY_F3((byte) 69),
    KEY_F4((byte) 70),
    KEY_F5((byte) 71),
    KEY_F6((byte) 72),
    KEY_F7((byte) 73),
    KEY_F8((byte) 74),
    KEY_F9((byte) 75),
    KEY_F10((byte) 76),
    KEY_NUM_LOCK((byte) 77),
    KEY_SCROLL_LOCK((byte) 78),
    KEY_KP_7((byte) 79),
    KEY_KP_8((byte) 80),
    KEY_KP_9((byte) 81),
    KEY_KP_SUBTRACT((byte) 82),
    KEY_KP_4((byte) 83),
    KEY_KP_5((byte) 84),
    KEY_KP_6((byte) 85),
    KEY_KP_ADD((byte) 86),
    KEY_KP_1((byte) 87),
    KEY_KP_2((byte) 88),
    KEY_KP_3((byte) 89),
    KEY_KP_0((byte) 90),
    KEY_KP_DEL((byte) 91),
    KEY_F11((byte) 95),
    KEY_F12((byte) 96),
    KEY_KP_ENTER((byte) 104),
    KEY_CTRL_R((byte) 105),
    KEY_KP_DIVIDE((byte) 106),
    KEY_PRTSCN((byte) 107),
    KEY_ALT_R((byte) 108),
    KEY_HOME((byte) 110),
    KEY_UP((byte) 111),
    KEY_PRIOR((byte) 112),
    KEY_LEFT((byte) 113),
    KEY_RIGHT((byte) 114),
    KEY_END((byte) 115),
    KEY_DOWN((byte) 116),
    KEY_NEXT((byte) 117),
    KEY_INSERT((byte) 118),
    KEY_DEL((byte) 119),
    KEY_MAX(KEY_DEL.id);

    public final byte id;

    XKeycode(byte id) { this.id = id; }

    public byte getId() { return id; }
}
